language: python
python:
  - 3.4
#  - pypy
addons:
  sonarqube: true
env:
  global:
    - secure: ********* # defines SONAR_TOKEN=abcdef0123456789
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN
